# 服务端地址 https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml
serverAddr = "117.72.202.85"
# 服务端配置的bindPort
serverPort = 7000

auth.method = "token"
auth.token = "***"

[[proxies]]
# 代理应用名称，根据自己需要进行配置
name = "local-ssh1"
# 代理类型 有tcp\udp\stcp\p2p
type = "tcp"
# 客户端代理应用IP
localIP = "host.docker.internal"  # 若mac Docker执行次条,mac docker运行在微型的linux中
# localIP = "127.0.0.1"

# 客户端代理应用端口
localPort = 22
# 服务端反向代理端口；提供给外部访问
remotePort = 6022


[[proxies]]
# 代理应用名称，根据自己需要进行配置
name = "app8080"
# 代理类型 有tcp\udp\stcp\p2p
type = "tcp"
# 客户端代理应用IP
localIP = "host.docker.internal"  # 若mac Docker执行次条,mac docker运行在微型的linux中
# localIP = "127.0.0.1"
# 客户端代理应用端口
localPort = 8080
# 服务端反向代理端口；提供给外部访问
remotePort = 18080